// Book names by USFM code. Hindi/Telugu from the IRV h headers (Telugu NT shortened).
export const BOOKS = {
  "GEN": { en: "Genesis", hi: "उत्पत्ति", te: "ఆదికాండం" },
  "EXO": { en: "Exodus", hi: "निर्गमन", te: "నిర్గమకాండం" },
  "LEV": { en: "Leviticus", hi: "लैव्यव्यवस्था", te: "లేవీకాండం" },
  "NUM": { en: "Numbers", hi: "गिनती", te: "సంఖ్యాకాండం" },
  "DEU": { en: "Deuteronomy", hi: "व्यवस्थाविवरण", te: "ద్వితీయోపదేశ కాండము" },
  "JOS": { en: "Joshua", hi: "यहोशू", te: "యెహోషువా" },
  "JDG": { en: "Judges", hi: "न्यायियों", te: "న్యాయాధిపతులు" },
  "RUT": { en: "Ruth", hi: "रूत", te: "రూతు" },
  "1SA": { en: "1 Samuel", hi: "1 शमूएल", te: "1 సమూయేలు" },
  "2SA": { en: "2 Samuel", hi: "2 शमूएल", te: "2 సమూయేలు" },
  "1KI": { en: "1 Kings", hi: "1 राजाओं", te: "1 రాజులు" },
  "2KI": { en: "2 Kings", hi: "2 राजाओं", te: "2 రాజులు" },
  "1CH": { en: "1 Chronicles", hi: "1 इतिहास", te: "1 దినవృత్తాంతాలు" },
  "2CH": { en: "2 Chronicles", hi: "2 इतिहास", te: "2 దినవృత్తాంతాలు" },
  "EZR": { en: "Ezra", hi: "एज्रा", te: "ఎజ్రా" },
  "NEH": { en: "Nehemiah", hi: "नहेम्याह", te: "నెహెమ్యా" },
  "EST": { en: "Esther", hi: "एस्तेर", te: "ఎస్తేరు" },
  "JOB": { en: "Job", hi: "अय्यूब", te: "యోబు" },
  "PSA": { en: "Psalm", hi: "भजन संहिता", te: "కీర్తనలు" },
  "PRO": { en: "Proverbs", hi: "नीतिवचन", te: "సామెతలు" },
  "ECC": { en: "Ecclesiastes", hi: "सभोपदेशक", te: "ప్రసంగి" },
  "SNG": { en: "Song of Solomon", hi: "श्रेष्ठगीत", te: "పరమ గీతము" },
  "ISA": { en: "Isaiah", hi: "यशायाह", te: "యెషయా" },
  "JER": { en: "Jeremiah", hi: "यिर्मयाह", te: "యిర్మీయా" },
  "LAM": { en: "Lamentations", hi: "विलापगीत", te: "విలాప వాక్యములు" },
  "EZK": { en: "Ezekiel", hi: "यहेजकेल", te: "యెహెజ్కేలు" },
  "DAN": { en: "Daniel", hi: "दानिय्येल", te: "దానియేలు" },
  "HOS": { en: "Hosea", hi: "होशे", te: "హోషేయ" },
  "JOL": { en: "Joel", hi: "योएल", te: "యోవేలు" },
  "AMO": { en: "Amos", hi: "आमोस", te: "ఆమోసు" },
  "OBA": { en: "Obadiah", hi: "ओबद्याह", te: "ఓబద్యా" },
  "JON": { en: "Jonah", hi: "योना", te: "యోనా" },
  "MIC": { en: "Micah", hi: "मीका", te: "మీకా" },
  "NAM": { en: "Nahum", hi: "नहूम", te: "నహూము" },
  "HAB": { en: "Habakkuk", hi: "हबक्कूक", te: "హబక్కూకు" },
  "ZEP": { en: "Zephaniah", hi: "सपन्याह", te: "జెఫన్యా" },
  "HAG": { en: "Haggai", hi: "हाग्गै", te: "హగ్గయి" },
  "ZEC": { en: "Zechariah", hi: "जकर्याह", te: "జెకర్యా" },
  "MAL": { en: "Malachi", hi: "मलाकी", te: "మలాకీ" },
  "MAT": { en: "Matthew", hi: "मत्ती", te: "మత్తయి" },
  "MRK": { en: "Mark", hi: "मरकुस", te: "మార్కు" },
  "LUK": { en: "Luke", hi: "लूका", te: "లూకా" },
  "JHN": { en: "John", hi: "यूहन्ना", te: "యోహాను" },
  "ACT": { en: "Acts", hi: "प्रेरितों के काम", te: "అపోస్తలుల కార్యములు" },
  "ROM": { en: "Romans", hi: "रोमियों", te: "రోమా" },
  "1CO": { en: "1 Corinthians", hi: "1 कुरिन्थियों", te: "1 కొరింతీ" },
  "2CO": { en: "2 Corinthians", hi: "2 कुरिन्थियों", te: "2 కొరింతీ" },
  "GAL": { en: "Galatians", hi: "गलातियों", te: "గలతీ" },
  "EPH": { en: "Ephesians", hi: "इफिसियों", te: "ఎఫెసీ" },
  "PHP": { en: "Philippians", hi: "फिलिप्पियों", te: "ఫిలిప్పీ" },
  "COL": { en: "Colossians", hi: "कुलुस्सियों", te: "కొలస్సయి" },
  "1TH": { en: "1 Thessalonians", hi: "1 थिस्सलुनीकियों", te: "1 తెస్సలోనీక" },
  "2TH": { en: "2 Thessalonians", hi: "2 थिस्सलुनीकियों", te: "2 తెస్సలోనీక" },
  "1TI": { en: "1 Timothy", hi: "1 तीमुथियुस", te: "1 తిమోతి" },
  "2TI": { en: "2 Timothy", hi: "2 तीमुथियुस", te: "2 తిమోతి" },
  "TIT": { en: "Titus", hi: "तीतुस", te: "తీతు" },
  "PHM": { en: "Philemon", hi: "फिलेमोन", te: "ఫిలేమోను" },
  "HEB": { en: "Hebrews", hi: "इब्रानियों", te: "హెబ్రీ" },
  "JAS": { en: "James", hi: "याकूब", te: "యాకోబు" },
  "1PE": { en: "1 Peter", hi: "1 पतरस", te: "1 పేతురు" },
  "2PE": { en: "2 Peter", hi: "2 पतरस", te: "2 పేతురు" },
  "1JN": { en: "1 John", hi: "1 यूहन्ना", te: "1 యోహాను" },
  "2JN": { en: "2 John", hi: "2 यूहन्ना", te: "2 యోహాను" },
  "3JN": { en: "3 John", hi: "3 यूहन्ना", te: "3 యోహాను" },
  "JUD": { en: "Jude", hi: "यहूदा", te: "యూదా" },
  "REV": { en: "Revelation", hi: "प्रकाशितवाक्य", te: "ప్రకటన" },
};
